apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb

resources:
  - https://raw.githubusercontent.com/metallb/metallb-operator/v0.13.11/bin/metallb-operator.yaml
  - metallb.yaml
  - ip_pool.yaml
  - l2_advertisement.yaml
