apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-sam-api-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: fast-sam-api.kubby.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-sam-api
                port:
                  number: 80