apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: label-studio-ingress
  namespace: label
spec:
  ingressClassName: nginx
  rules:
    - host: label-studio.kubby.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: label-studio-ls-app
                port:
                  number: 80