apiVersion: v1
kind: Service
metadata:
  name: fast-sam-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fast-sam-api
    app.kubernetes.io/instance: fast-sam-api