---
# Source: kafka-ui/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "v0.4.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka
---
# Source: kafka-ui/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "v0.4.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka
type: Opaque
data:
---
# Source: kafka-ui/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "v0.4.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka
data:
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_CLUSTERS_0_NAME: kafka
  KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper-client.kafka.svc.cluster.local:2181
---
# Source: kafka-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "v0.4.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30110
  selector:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
---
# Source: kafka-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "v0.4.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
      app.kubernetes.io/instance: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/instance: kafka-ui
    spec:
      serviceAccountName: kafka-ui
      securityContext:
        {}
      containers:
        - name: kafka-ui
          securityContext:
            {}
          image: docker.io/provectuslabs/kafka-ui:v0.4.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: kafka-ui    
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {}