apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dask
manifests:
  helm:
    releases:
      - name: dask
        remoteChart: dask
        namespace: dask
        version: 2023.1.0
        createNamespace: false
        repo: https://helm.dask.org/
        setValues:
          scheduler.serviceType: NodePort
          worker.replicas: 4
          jupyter.enabled: false
          worker.resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 2
              memory: 4Gi
          worker.custom_scheduler_url: "tcp://dask-scheduler.dask.svc.cluster.local:8786"
          worker.env:
            - name: EXTRA_PIP_PACKAGES
              value: |
                dask-ml[complete]==2023.3.24 \
                opencv-python-headless==4.7.0.72 \
                streamz==0.6.4 \
                kafka-python==2.0.2 \
                zarr==2.14.2 \
                deltalake==0.8.1 \
                s3fs \
                boto3 \
                --upgrade
deploy:
  helm: {}