apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dask
manifests:
  helm:
    releases:
      - name: dask
        remoteChart: dask
        namespace: dask
        version: 2023.1.0
        createNamespace: true
        repo: https://helm.dask.org/
        setValues:
          scheduler.serviceType: NodePort
          worker.replicas: 4
          jupyter.enabled: false
          scheduler.image.tag: 2023.3.2-py3.10
          worker.image.repository: jackmead515/dask-worker
          worker.image.tag: v5
          worker.custom_scheduler_url: "tcp://dask-scheduler.dask.svc.cluster.local:8786"
          scheduler.affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - jack-pc
          worker.affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - jack-pc
                          - dellpoweredget110
          worker.mounts:
            volumes:
              - name: data
                emptyDir:
                  medium: Memory
                  sizeLimit: 64Mi
            volumeMounts:
              - mountPath: /tmp/data
                name: data
          worker.env:
            - name: S3_ACCESS_KEY_ID
              value: admin
            - name: S3_SECRET_ACCESS_KEY
              value: admin123

deploy:
  helm: {}