apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dask
manifests:
  helm:
    releases:
      - name: dask
        remoteChart: dask
        namespace: dask
        version: 2023.1.0
        createNamespace: false
        repo: https://helm.dask.org/
deploy:
  helm: {}