apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kube-prometheus
manifests:
  helm:
    releases:
      - name: kube-prometheus
        remoteChart: kube-prometheus-stack
        namespace: monitoring
        version: 44.3.0
        createNamespace: false
        repo:  https://prometheus-community.github.io/helm-charts
        setValues:


          # ALERT MANAGER SETTINGS
          alertmanager.alertmanagerSpec.replicas: 2
          alertmanager.alertmanagerSpec.alertmanagerConfigSelector:
            matchLabels:
              alertmanager: config
          alertmanager.alertmanagerSpec.retention: 120h
          alertmanager.alertmanagerSpec.storage: {}


          # GRAFANA SETTINGS
          grafana.defaultDashboardsTimezone: utc
          grafana.adminPassword: admin
          grafana.service.type: NodePort
          grafana.service.nodePort: 30100


          # PROMETHEUS SETTINGS
          prometheus.prometheusSpec.scrapeInterval: 30s
          prometheus.prometheusSpec.scrapeTimeout: 10s
          prometheus.prometheusSpec.enableAdminAPI: false
          prometheus.prometheusSpec.enableFeatures:
            - exemplar-storage
          prometheus.prometheusSpec.additionalArgs:
            - name: query.lookback-delta
              value: '1m'
          prometheus.prometheusSpec.retention: 120h
          prometheus.prometheusSpec.replicas: 1
          prometheus.prometheusSpec.storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: local-path
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 20Gi


          # PROMETHEUS OPERATOR SETTINGS
          prometheusOperator.namespaces: ''
          prometheusOperator.denyNamespaces: ''
          prometheusOperator.prometheusInstanceNamespaces: ''
          prometheusOperator.alertmanagerInstanceNamespaces: ''
          prometheusOperator.thanosRulerInstanceNamespaces: ''
          prometheusOperator.prometheusConfigReloader.resources:
            limits:
              cpu: 32m
              memory: 128Mi
            requests:
              cpu: 32m
              memory: 128Mi
deploy:
  helm: {}