apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: main
requires:
  - configs: [metallb]
    path: metallb.yaml
  - configs: [ingress-nginx]
    path: ingress-nginx.yaml
  - configs: [ingress]
    path: ingress.yaml
  - configs: [kube-prometheus]
    path: kube-prometheus.yaml
  - configs: [strimzi]
    path: strimzi.yaml
  - configs: [dask]
    path: dask.yaml
  - configs: [minio]
    path: minio.yaml
  - configs: [label-studio]
    path: label-studio.yaml