apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: minio
manifests:
  helm:
    releases:
      - name: minio
        remoteChart: minio
        namespace: minio
        version: 12.1.13
        createNamespace: true
        repo: https://charts.bitnami.com/bitnami
        setValues:
          service.type: "NodePort"
          service.nodePorts.api: "30140"
          service.nodePorts.console: "30141"
          auth.rootPassword: "admin123"
          statefulset.replicaCount: 4
          persistence.size: "50Gi"
          mode: "distributed"
deploy:
  helm: {}